import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

export default function Home({posts}) {


  const url =
    "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1888&q=80";
  const img_url =
    "https://images.unsplash.com/photo-1499750310107-5fef28a66643?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80";

  return (
    <div>
      <Head>
        <title>Aashraya Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Header/>
<div style={{background:"black",height:"300px"}}>
  <img src={img_url} style={{width:"100%",height:"300px",opacity:"0.4",}} />
  <h1 style={{textAlign:"center",position:"absolute",color:"white",left:"50%",top:"15%",letterSpacing:"2px"}}>BLOGS</h1>
</div>
      <main style={{padding:"0px",margin:"0px"}}>
        <div className="container-card">
          <div className="card">
            <div className="card-heading-container-1">
              <img src={img_url} />
              <div>
                <h1>HEADING OR TITLE</h1>
                <span>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever since the 1500s, when an unknown
                  printer took a galley of type and scrambled it to make a type
                  specimen book. It has survived not only five centuries,
                </span>
                <p>See More</p>
              </div>
            </div>
            <div className="card-heading-container-2">
              <img src={url} alt="writer image" />
              <div className="info-writer">
                <span>Writer :Radhika Agarwal</span>
                <span>NITK Surathkal</span>
                <span>Guwahati, Assam</span>
              </div>
            </div>
          </div>

          <div className="card">
            <div className="card-heading-container-1">
              <img src={img_url} />
              <div>
                <h1>HEADING OR TITLE</h1>
                <span>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever since the 1500s, when an unknown
                  printer took a galley of type and scrambled it to make a type
                  specimen book. It has survived not only five centuries,
                </span>
                <p>See More</p>
              </div>
            </div>
            <div className="card-heading-container-2">
              <img src={url} alt="writer image" />
              <div className="info-writer">
                <span>Writer :Radhika Agarwal</span>
                <span>NITK Surathkal</span>
                <span>Guwahati, Assam</span>
              </div>
            </div>
          </div>

          <div className="card">
            <div className="card-heading-container-1">
              <img src={img_url} />
              <div>
                <h1>HEADING OR TITLE</h1>
                <span>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever since the 1500s, when an unknown
                  printer took a galley of type and scrambled it to make a type
                  specimen book. It has survived not only five centuries,
                </span>
                <p>See More</p>
              </div>
            </div>
            <div className="card-heading-container-2">
              <img src={url} alt="writer image" />
              <div className="info-writer">
                <span>Writer :Radhika Agarwal</span>
                <span>NITK Surathkal</span>
                <span>Guwahati, Assam</span>
              </div>
            </div>
          </div>

          <div className="card">
            <div className="card-heading-container-1">
              <img src={img_url} />
              <div>
                <h1>HEADING OR TITLE</h1>
                <span>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever since the 1500s, when an unknown
                  printer took a galley of type and scrambled it to make a type
                  specimen book. It has survived not only five centuries,
                </span>
                <p>See More</p>
              </div>
            </div>
            <div className="card-heading-container-2">
              <img src={url} alt="writer image" />
              <div className="info-writer">
                <span>Writer :Radhika Agarwal</span>
                <span>NITK Surathkal</span>
                <span>Guwahati, Assam</span>
              </div>
            </div>
          </div>

          <div className="card">
            <div className="card-heading-container-1">
              <img src={img_url} />
              <div>
                <h1>HEADING OR TITLE</h1>
                <span>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever since the 1500s, when an unknown
                  printer took a galley of type and scrambled it to make a type
                  specimen book. It has survived not only five centuries,
                </span>
                <p>See More</p>
              </div>
            </div>
            <div className="card-heading-container-2">
              <img src={url} alt="writer image" />
              <div className="info-writer">
                <span>Writer :Radhika Agarwal</span>
                <span>NITK Surathkal</span>
                <span>Guwahati, Assam</span>
              </div>
            </div>
          </div>

        </div>
      </main>
      <nav style={{height:"100px"}}></nav>
    </div>
  );
}


export async function getServerSideProps(){

  const res = await fetch(`${baseUrl}/api/post`)
  const posts = await res.json()
  return{

      props:{
          posts
      }
  }
}